---

- hosts: vault-servers
  vars:
    nginxle_version: v0.1.4
    vault_version: 0.9.0

  vars_files:
    - vars/secrets.yml

  roles:
    - role: Luzifer.ubuntu-unattended-upgrades
      mail_target: knut@ahlers.me
      reboot_time: 04:00
      do_reboot: "true"
      do_autoremove: "true"
    
  tasks:
    - name: Install unzip
      apt:
        name: unzip
        update_cache: True

    # vault related

    - name: Get Vault version
      command: '/usr/local/bin/vault --version'
      register: check_vault_version

    - name: Install vault binary
      unarchive:
        src: 'https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip'
        dest: /usr/local/bin
        remote_src: True
      when: '"Vault v{{ vault_version }}" not in check_vault_version.stdout'
      register: install_vault_binary

    - name: Configure vault
      template:
        src: vault.hcl
        dest: /etc/vault.hcl
        mode: 0600
      register: configure_vault

    - name: Install vault service configuration
      template:
        src: vault.service
        dest: /etc/systemd/system/vault.service

    - name: Activate and start Vault
      service:
        name: vault
        enabled: True
        state: started

    - name: Restart Vault on changes
      service:
        name: vault
        state: restarted
      when: install_vault_binary.changed or configure_vault.changed

    # nginx-letsencrypt related

    - name: Install nginx as a proxy server
      apt:
        name: nginx
        update_cache: True
        state: latest

    - name: Stop and disable nginx service
      service:
        name: nginx
        enabled: False
        state: stopped

    - name: Install nginx configuration
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Install nginx-letsencrypt
      get_url:
        url: 'https://github.com/Luzifer/nginx-letsencrypt/releases/download/{{ nginxle_version }}/nginx-letsencrypt_linux_amd64'
        dest: /usr/local/bin/nginx-letsencrypt
        mode: 0755

    - name: Install nginx-letsencrypt service configuration
      template:
        src: nginx-letsencrypt.service
        dest: /etc/systemd/system/nginx-letsencrypt.service

    - name: Activate and start nginx-letsencrypt
      service:
        name: nginx-letsencrypt
        enabled: True
        state: started

    - name: Enable fail2ban for SSH
      apt:
        name: fail2ban

    - name: Set up logrotate for audit logs
      copy:
        dest: /etc/logrotate.d/vault
        content: |
          /var/log/vault/audit.log {
            missingok
            notifempty
            compress
            copytruncate
            daily
            maxsize 100M
            rotate 7
          }
